name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Deploy when the main branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Adjust the Python version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to PythonAnywhere
      env:
        WORKON_HOME: ${{ github.workspace }}/venv
        USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
      run: |
        source venv/bin/activate
        pip install pythonanywhere
        # Use a direct command for deployment without relying on virtualenvwrapper
        python -m pythonanywhere.pa_autoconfigure_django https://github.com/Kingsleyrhema/bgm.git
        python -m pythonanywhere.pa_reload_webapp bgmweb.pythonanywhere.com
