name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Deploy when the main branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Adjust the Python version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install pythonanywhere
      run: |
        source venv/bin/activate
        pip install requests  # Install requests for API calls

    - name: Deploy to PythonAnywhere
      env:
        USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        DOMAIN_NAME: 'bgmweb'  # Your domain name part
      run: |
        source venv/bin/activate
        python -c "
        import requests

        def reload_webapp(username, token, domain_name):
            headers = {'Authorization': f'Token {token}'}
            url = f'https://www.pythonanywhere.com/api/v1/user/{username}/websites/{domain_name}/reload/'
            response = requests.post(url, headers=headers)
            if response.status_code == 200:
                print('Deployment successful')
            else:
                print(f'Error: {response.status_code} - {response.content}')

        reload_webapp('$USERNAME', '$API_TOKEN', '$DOMAIN_NAME')
        "
